The task 5

diff --git a/Advanced_shell/batchProcessing-0x04 b/Advanced_shell/batchProcessing-0x04
--- a/Advanced_shell/batchProcessing-0x04
+++ b/Advanced_shell/batchProcessing-0x04
@@ -29,4 +29,14 @@ jobs
 # Wait for all jobs to finish
 wait
 
+
+# Wait for all fetches to complete
+for pid in "${PIDS[@]}"; do
+    wait "$pid" || {
+        echo "A background process failed. Killing all remaining..."
+        kill "${PIDS[@]}" 2>/dev/null
+        exit 1
+    }
+done
+
 echo "✅ All fetches completed."
